version: '3.7'
services:
  app:
    build: .
    image: friends_judge
    command: bundle exec puma -C config/puma.rb
    ports:
      - 5001:3000
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - .:/var/www/friends_judge

  db:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=friends_judge_development
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./docker/db/etc:/etc/mysql/conf.d
      - sql_data:/var/lib/mysql

volumes:
  sql_data:
    driver: local